### PR TITLE
make it compatible with django 2.1

### PR DESCRIPTION
**Pull request by mehdipourfar**

### CODE REVIEW

**Comment by basask** [comment]
Hi, @mehdipourfar
Thank you for this PR. 
Supporting multiple schemas and python 2.1 will be a great addition to this repo.
I am the creator of this project but I no longer work in this organization anymore so I cannot merge the PR.
I think @arianerocha and/or @tewald could do that after their reviews.
Thanks again!

**Comment by mehdipourfar** [comment]
Thanks @basask for this very useful package. I think more people will be using it if they find out what can they do with it.

**Review by tewald — APPROVED** [review]
Sorry for the long wait.  
I don't see any problems with this PR.  
Thanks for contributing!

**Comment by mehdipourfar** [comment]
Thanks a lot. Could you merge and update it on pip?

**Comment by srugano** [comment]
Would really appreciate this PR.

**Comment by thomas-ewald** [comment]
Sorry for the delay.
:-)

**Comment by mehdipourfar** [comment]
You're welcome. It will be great if you update pypi.

**Comment by thomas-ewald** [comment]
> You're welcome. It will be great if you update pypi.

Done!

**Comment by srugano** [comment]
I'm trying to implement the example provided but have hard time coming with a working example.

**Pull request merged**
